### PR TITLE
Add a copy of the BSD 2-Clause license

### PR DESCRIPTION
**Pull request by Calinou**
It is good practice to add a copy of the license to the repository.

(Note: I saw the license of the project [here](https://nodei.co/npm/torrent/).)

### CODE REVIEW

**Comment by LinusU** [comment]
Why is it good practice? It's specified in the `package.json` file.

**Comment by Calinou** [comment]
See [Do I really need to include a licence file for common licences like GPL or MIT?](http://opensource.stackexchange.com/questions/176/do-i-really-need-to-include-a-licence-file-for-common-licences-like-gpl-or-mit/180#180)

**Comment by LinusU** [comment]
Yuck, I hate having license information in the top of each file :(

Personally I would probably skip it on the grounds that I'm lazy, but it'll be up to @maxogden to decide how he wants to do.

On a semirelated note, githubs choosealicense.com recommends the ISC license instead and says that:

> The ISC license is functionally equivalent to the BSD 2-Clause and MIT licenses, removing some language that is no longer necessary.

Maybe we should use that one instead? The text is shorter \o/

**Comment by Calinou** [comment]
[choosealicense.com](http://choosealicense.com/) recommends MIT more than ISC.

If you are going to change the license, I recommend you pick MIT.

**Comment by LinusU** [comment]
Hmm, interesting, well my preference is MIT as well; but it's up to **maxogden** to decide

**Pull request closed without merging**
