### PR TITLE
JavaScript Standard Style

### PR DESCRIPTION
**Pull request by feross**
https://github.com/feross/standard

### CODE REVIEW

**Comment by LinusU** [comment]
@maxogden Would you be open to merge an updated version of this? It seems like we are really close in coding standard already.

I could create the updated version :)

**Comment by maxogden** [comment]
yea +1

**Comment by LinusU** [comment]
Fixed in a6d0d0a

**Comment by maxogden** [comment]
nice, thanks

On Wednesday, June 17, 2015, Linus Unnebäck <notifications@github.com>
wrote:

> Closed #27 <https://github.com/maxogden/torrent/pull/27>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maxogden/torrent/pull/27#event-332907464>.
>


-- 
Sent from my phone

**Pull request closed without merging**
