### PR TITLE
Added travis ci support for modern node versions

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by LinusU** [comment]
I would personally prefer it if we dropped `5` here since it's not a maintained release line. Also, if it works on 4 and 6 than it probably works on `5` as well.

Thoughts?

**Comment by amilajack** [comment]
I think that's fine. Doesn't make too much of a difference. Not sure why these old versions of node are still being used tho. They have older versions of v8 and lack ES6 support.

**Comment by LinusU** [comment]
Do you want to drop `5` as well?

**Comment by amilajack** [comment]
Lets keep it just in case there's some nasty bug that's only in node 5. Better safe than sorry? And it only adds a few minutes to the test.

**Comment by LinusU** [comment]
Fair enough 👍

**Pull request merged**
